### ISSUE TITLE
【调整】adi编辑区增加当前编辑模块的类型名称

### ISSUE THREAD

**Issue by azothli** [tatfook/KeepWorkDesgin#19]
现在不好确认我编辑的是什么模块

**Comment by azothli** [comment]
![image](https://user-images.githubusercontent.com/22001356/39283134-5f4841cc-493f-11e8-8687-cb958a1ab8a4.png)

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/40293703-bb431334-5d04-11e8-9ecf-808362d943ba.png)
设计稿已完成  待开发

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/40293717-d06dcd80-5d04-11e8-9fbb-63a344647ff3.png)
svn--源文件
