### ISSUE TITLE
KW2.0 - 网站layout&theme 设置

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/KeepWorkDesgin#2]
### 背景

[layout 程序设计](http://keepwork.com/keepwork/pwiki/pm/ADI%E7%BC%96%E8%BE%91%E5%99%A8%E6%94%B9%E7%89%88/layout%E8%AE%BE%E8%AE%A1)

基于新的设计需求，我们需要在网站设置中添加theme和layout板块。
theme板块的功能相对简单，基本思路为选择一个theme，选择font和color即可。
layout则比较复杂，我们需要添加layout以及其相关的header、footer等md文件。但是，这些操作必须以常规的交互操作来实现。

另外，viewport页面也需要根据layout来做调整。以便用户直接在viewport中编辑layout。

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/39510552-a57682b2-4e1c-11e8-868b-e058798ca80e.png)
![image](https://user-images.githubusercontent.com/33826048/39510565-adbe5152-4e1c-11e8-873b-bf263fc5f5c4.png)
![image](https://user-images.githubusercontent.com/33826048/39510575-b8424bc4-4e1c-11e8-877d-5fd07a6803cf.png)

**Comment by wanglin727** [comment]
设计已完成   转开发跌段
