### ISSUE TITLE
【需求】代码编辑窗：添加mod按钮

### ISSUE THREAD

**Issue by azothli** [tatfook/KeepWorkDesgin#29]
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/05fba578-2e5d-43c8-a8e6-137e07be65ba)

**Comment by azothli** [comment]
Mod

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/39735242-4badb8dc-52ad-11e8-83d1-e163fd40dae9.png)


用现有的icon
