### ISSUE TITLE
KW2.0 - 网盘功能

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/KeepWorkDesgin#3]
基于新的页面交互，调整模块入口，并根据整体样式和交互，检查是否需要做细节调整

**Comment by azothli** [comment]
![image](https://user-images.githubusercontent.com/22001356/39396027-43ffce40-4b19-11e8-9813-9d55600217f6.png)
![image](https://user-images.githubusercontent.com/22001356/39396036-678a239c-4b19-11e8-96db-f4fdc13c924b.png)

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/40293633-739b94e8-5d04-11e8-9990-4a025f149ed6.png)
设计稿已完成  待开发

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/40293678-9a5f9688-5d04-11e8-84b4-b358f522a801.png)


svn-源文件
