### ISSUE TITLE
【调整】adi 模块：多行文编辑功能优化

### ISSUE THREAD

**Issue by azothli** [tatfook/KeepWorkDesgin#32]
多行文本编辑，属于用户主要的内容创建行为。
在多行文本的编辑中，现在需要视觉一直盯着左侧的adi编辑区，不友好。
在多行文本编辑状态（多行文本控件、md控件等），增加一个弹出按钮。
点击后，在视觉中心展开编辑窗口，让用户可以轻松的创作。

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/40293801-25c25634-5d05-11e8-8a8c-5ebb4f8414e0.png)
设计稿已完成   待开发

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/40293818-33fd418c-5d05-11e8-9b79-f3a273f0b6b7.png)
svn--源文件
