### ISSUE TITLE
【editor-文件树】建议增加文件移动功能，便于调整文件归档到文件夹里

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/KeepWorkDesgin#34]
### 问题：
当网页文件过多后，需要将文件进行归档处理，但目前没有移动文件的功能，只能重新复制新建，用户操作繁琐，建议增加文件移动功能

**Comment by ouyc** [comment]
Issue moved to [tatfook/keepwork #2333](https://github.com/tatfook/keepwork/issues/2333) via [**ZenHub**](https://www.zenhub.com/)
