### ISSUE TITLE
【需求】添加保存全部、关闭全部按钮

### ISSUE THREAD

**Issue by azothli** [tatfook/KeepWorkDesgin#38]
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/15809220-6652-4904-8e5b-fef50a3a4dfb)

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/40411321-aab95538-5ea2-11e8-82b1-51544ece56d1.png)


源文件 svn
