### ISSUE TITLE
【调整】考虑mouseover才显示操作按钮，现在太乱

### ISSUE THREAD

**Issue by azothli** [tatfook/KeepWorkDesgin#39]
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/53dead49-66db-4082-bae6-15d90aacc35f)

**Comment by wanglin727** [comment]
开始设计就是mouseover 出现icon，转开发

**Comment by ouyc** [comment]
Issue moved to [tatfook/keepwork #713](https://github.com/tatfook/keepwork/issues/713) via [**ZenHub**](https://www.zenhub.com/)
