### ISSUE TITLE
【设计】文件树的结构目录显示两个icon了，请调整设计

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/KeepWorkDesgin#41]
## 操作：
1.进入Editor页面，打开一个存在多级目录的网站进行查看，观察目录结构及显示效果

![ui_icon.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/48d4a34b-aa48-40e7-8e97-726842621ba4)

**Comment by wanglin727** [comment]
2个icon是按设计稿来的，类似：
![image](https://user-images.githubusercontent.com/33826048/40407202-3beb2a34-5e96-11e8-9bca-30a292042784.png)

**Comment by Sandu1213** [comment]
意思是：上层网站还是需要的，文件夹图标就不需要左侧的折叠项了，建议找时间与西峙直接沟通下。
