### ISSUE TITLE
【需求】目前mod的目录和mod对象不容易区分辨识，请优先调整下

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/KeepWorkDesgin#42]
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/04f80e64-a2a6-4d35-99d5-e395f7617894)

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/40357762-bf81008c-5def-11e8-9021-7ef4856171a2.png)
![image](https://user-images.githubusercontent.com/33826048/40357780-cdfe7afe-5def-11e8-8265-de5097e0007c.png)
![image](https://user-images.githubusercontent.com/33826048/40357879-187596da-5df0-11e8-9d90-e62692066777.png)

源文件--svn

**Comment by wanglin727** [comment]
源文件 Svn
文件路径： 新版ADI     #42目录list
