### ISSUE TITLE
【mod】搜索mod

### ISSUE THREAD

**Issue by azothli** [tatfook/KeepWorkDesgin#46]
设置搜索条件，格式化返回结果

**Comment by Kvaya** [comment]
1.在菜单栏中的“交互“项加子项“搜索”，搜索样式如下图：
![image](https://user-images.githubusercontent.com/39363297/46184097-9e6d8d80-c306-11e8-975e-e92481ee54f3.png)
![image](https://user-images.githubusercontent.com/39363297/46184373-f658c400-c307-11e8-99af-1c6cb99c50c7.png)
2.搜索属性如下图：
![image](https://user-images.githubusercontent.com/39363297/46184228-2e133c00-c307-11e8-8b15-11b6070c883f.png)

**Comment by Kvaya** [comment]
Issue moved to [tatfook/keepwork #2325](https://github.com/tatfook/keepwork/issues/2325) via [**ZenHub**](https://www.zenhub.com/)
