### ISSUE TITLE
编辑器 系统菜单样式调整

### ISSUE THREAD

**Issue by wanglin727** [tatfook/KeepWorkDesgin#47]
![image.png](https://images.zenhubusercontent.com/5a1298d08a75884b908813d2/f62b6dc0-32d8-462b-a34a-75deaa1d2293
![image](https://user-images.githubusercontent.com/33826048/40656434-ef629bd0-6376-11e8-9e34-eb634819977b.png)

![image.png](https://images.zenhubusercontent.com/5a1298d08a75884b908813d2/9fa022b2-697c-4eee-8a0c-bf3b85e94613)

**Comment by enya-i** [comment]
![default](https://user-images.githubusercontent.com/37529364/41276300-66e3ee9a-6e56-11e8-916d-51d03a5726e1.jpg)

**Comment by enya-i** [comment]
Issue moved to [tatfook/keepwork #845](https://github.com/tatfook/keepwork/issues/845) via [**ZenHub**](https://www.zenhub.com/)

**Comment by enya-i** [comment]
Issue moved to [tatfook/keepwork #846](https://github.com/tatfook/keepwork/issues/846) via [**ZenHub**](https://www.zenhub.com/)
