### ISSUE TITLE
【调整】个人设置中心

### ISSUE THREAD

**Issue by azothli** [tatfook/KeepWorkDesgin#50]
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/34900d91-9338-4485-94c2-b1a18e0110d4)

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/41087446-4e4f303c-6a6f-11e8-855f-71f156520d36.png)

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/41087571-a50b9866-6a6f-11e8-859c-bc7e425391ab.png)
设计稿 svn

**Comment by wanglin727** [comment]
Issue moved to [tatfook/keepwork #802](https://github.com/tatfook/keepwork/issues/802) via [**ZenHub**](https://www.zenhub.com/)
