### ISSUE TITLE
【需求】资源非正常状态占位

### ISSUE THREAD

**Issue by azothli** [tatfook/KeepWorkDesgin#55]
增加额外的图片、视频在以下状态的替换显示内容：
资源审核中
无访问权限
未找到指定资源

**Comment by enya-i** [comment]
![default](https://user-images.githubusercontent.com/37529364/41096921-c680492e-6a88-11e8-983c-e145335ca340.png)
![default](https://user-images.githubusercontent.com/37529364/41096922-c6875c3c-6a88-11e8-98b1-bd0de4eef8b5.png)
![default](https://user-images.githubusercontent.com/37529364/41096924-c79d248a-6a88-11e8-89d4-2474e376cfe8.png)
