### ISSUE TITLE
【需求】网站封停，提醒页面设计

### ISSUE THREAD

**Issue by azothli** [tatfook/KeepWorkDesgin#6]
您访问的网站暂时停止服务，请稍后再试。

可以参考已有的404页面

**Comment by enya-i** [comment]
![tim 20180409173514](https://user-images.githubusercontent.com/37529364/38490773-99afdfbc-3c1c-11e8-8614-0afa69663291.png)

**Comment by enya-i** [comment]
![tim 20180409173527](https://user-images.githubusercontent.com/37529364/38490793-a3ce929a-3c1c-11e8-83e2-23ac8532614e.png)

**Comment by azothli** [comment]
按钮名称调成 【返回】
如果有上一页就会上一页面，没有就回首页

**Comment by enya-i** [comment]
好的

**Comment by azothli** [comment]
@ouyc  可能完成了，确定下是否关闭

**Comment by ouyc** [comment]
郑嘉彪已完成用户账号被封停的时候显示此页面
