### ISSUE TITLE
【需求调整】需要出设计图的需求清单

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/KeepWorkDesgin#60]
- 显示代码
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/b9be94ce-b529-4821-b2d6-7f70d43666a5)

- 颜色区分
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/8582c859-e105-4cfe-aa57-a2b8ce2bb4e1)

- 编辑器(我创建的网站)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/6183938a-0960-4c01-84f9-85d6a80ec6e5)

**Comment by enya-i** [comment]
![default](https://user-images.githubusercontent.com/37529364/41345945-a86691a6-6f37-11e8-99db-20a4b466fdea.png)
![zen mode](https://user-images.githubusercontent.com/37529364/41345955-b004453e-6f37-11e8-9da3-1dcc4d99bb5f.png)

**Comment by enya-i** [comment]
Issue moved to [tatfook/keepwork #864](https://github.com/tatfook/keepwork/issues/864) via [**ZenHub**](https://www.zenhub.com/)
