### ISSUE TITLE
【需求】请设计一个可以快速返回顶部的页面设计图

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/KeepWorkDesgin#64]
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/bd0233ff-c58c-4d4d-a22b-9e37889d1431)

**Comment by enya-i** [comment]
![image](https://user-images.githubusercontent.com/37529364/41215254-141abd30-6d82-11e8-82ae-2c0df144f9e6.png)

**Comment by enya-i** [comment]
Issue moved to [tatfook/keepwork #844](https://github.com/tatfook/keepwork/issues/844) via [**ZenHub**](https://www.zenhub.com/)
