### ISSUE TITLE
【bug、需求】MD的文本， 预览框鼠标放上去就是一个大大的蓝色罩住整个屏幕

### ISSUE THREAD

**Issue by ouyc** [tatfook/KeepWorkDesgin#68]
@duting1993 commented on [Fri May 18 2018](https://github.com/tatfook/keepwork/issues/559)

![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/061fa970-dbdc-47e9-b60e-69ed135fbf7f)

---

@duting1993 commented on [Fri May 18 2018](https://github.com/tatfook/keepwork/issues/559#issuecomment-390079966)

@azothli

**Comment by enya-i** [comment]
![image](https://user-images.githubusercontent.com/37529364/41454498-2ebee292-70ac-11e8-84ae-de74a133c8b3.png)


改动：
鼠标移入时，取消掉原有的蓝色遮罩，
标示模块范围的虚线框由蓝色变为橙色，
鼠标移出后，颜色变为原来的蓝色,
变换时给个过渡。

**Comment by enya-i** [comment]
Issue moved to [tatfook/keepwork #902](https://github.com/tatfook/keepwork/issues/902) via [**ZenHub**](https://www.zenhub.com/)
