### ISSUE TITLE
【iicc】banner中英文文字调整

### ISSUE THREAD

**Issue by azothli** [tatfook/KeepWorkDesgin#69]
国际智能创意大奖赛 英文翻译确定为：International Intelligence & Creativity Contest  简称：IICC

图片改好了，找前端替换

**Comment by enya-i** [comment]
![image](https://user-images.githubusercontent.com/37529364/41459863-64dc47a0-70bd-11e8-9232-083009ba2b9f.png)

**Comment by enya-i** [comment]
Issue moved to [tatfook/keepwork #912](https://github.com/tatfook/keepwork/issues/912) via [**ZenHub**](https://www.zenhub.com/)
