### ISSUE TITLE
【调整】vip功能说明

### ISSUE THREAD

**Issue by azothli** [tatfook/KeepWorkDesgin#75]
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/482f0a85-0c9d-4182-9e48-fecba88628a2)
红色部分去除
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/760c45de-f7ab-493a-ada6-cdf5edd6b722)

**Comment by ouyc** [comment]
Issue moved to [tatfook/keepwork #1022](https://github.com/tatfook/keepwork/issues/1022) via [**ZenHub**](https://www.zenhub.com/)
