### ISSUE TITLE
【网站设置】布局设置

### ISSUE THREAD

**Issue by azothli** [tatfook/KeepWorkDesgin#8]
见rp

**Comment by azothli** [comment]
https://assets.npl.lan:4403/svn/UI_resource/keepwork2018.rp

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/39033698-dedf9f82-44a5-11e8-8a20-f16f52f31725.png)

**Comment by wanglin727** [comment]
源文件   已上传svn
