### ISSUE TITLE
【bug】adi mod中，有的url设定没有下拉选择本网站内容的部分

### ISSUE THREAD

**Issue by azothli** [tatfook/KeepWorkDesgin#86]
应该是这样的
![image](https://user-images.githubusercontent.com/22001356/44637533-43353c00-a9e4-11e8-9de1-728c5dd8a1e3.png)

检查到哪里没有，转big调整

**Comment by Sandu1213** [comment]
该issue 已转为 [#1805](https://github.com/tatfook/keepwork/issues/1805)来跟进，问题关闭。
