### ISSUE TITLE
【优化】视频封面

### ISSUE THREAD

**Issue by azothli** [tatfook/KeepWorkDesgin#88]
目前视频载入后会展示第一帧，视频如果没有特意处理，效果不好。
添加设置封面的功能

**Comment by azothli** [comment]
![image](https://user-images.githubusercontent.com/22001356/45856368-bf723380-bd86-11e8-8284-402a3a5488f4.png)

**Comment by Kvaya** [comment]
在“SVN/editor mod/新增mod ”文档中，“视频属性”及“点击添加视频封面”原型页中标明视频属性及添加视频封面效果等。参考开发

**Comment by ouyc** [comment]
Issue moved to [tatfook/keepwork #2331](https://github.com/tatfook/keepwork/issues/2331) via [**ZenHub**](https://www.zenhub.com/)
