### ISSUE TITLE
当属性面板所有的开关closed，预览区对应的mod被隐藏，现空白显示不是被隐藏了

### ISSUE THREAD

**Issue by ouyc** [tatfook/KeepWorkDesgin#89]
@Kvaya commented on [Tue Oct 09 2018](https://github.com/tatfook/keepwork/issues/2399)

当属性面板所有的开关closed，预览区对应的mod被隐藏，这块区域需给用户提醒，该区域是被隐藏的；在新的窗口浏览时，这块区域是不被显示的，且下面内容上移覆盖该区域。

**Comment by wanglin727** [comment]
设计稿如下
![image](https://user-images.githubusercontent.com/33826048/46650992-16726800-cbd1-11e8-84ae-0d9cf2fc37b5.png)

![image](https://user-images.githubusercontent.com/33826048/46651390-66056380-cbd2-11e8-9a61-92ceaa7cfde1.png)

**Comment by Kvaya** [comment]
Issue moved to [tatfook/keepwork #2413](https://github.com/tatfook/keepwork/issues/2413) via [**ZenHub**](https://www.zenhub.com/)
